version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_crm
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: crm_vape

volumes:
  mongo_data:
